/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.pbd.view;

/**
 *
 * @author Andre-Coude
 */
public class DiaMensagem extends javax.swing.JDialog {

    /**
     * Creates new form DiaPagamento
     */
    private final String EDICAO, CAMPOS, SENHA, CADASTRO, EXCLUSAO, ERRO, ERROLOGIN,
            CADASTREPRO, AGENDADO, EXCLUSAONAO, ADDPRODUTO, SEMESTOQUE,RESET,CAIXAFECHADO;

    public DiaMensagem(javax.swing.JFrame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.EDICAO = "EDIÇÃO FINALIZADA!";
        this.CAMPOS = "HÁ CAMPOS OBRIGATORIOS VAZIOS!";
        this.SENHA = "SENHAS DIFERENTES!";
        this.CADASTRO = "CADASTRO CONCLUIDO!";
        this.EXCLUSAO = "EXCLUSAO FINALIZADA!";
        this.EXCLUSAONAO = "EXCLUSAO NAO PERMITIDA!";
        this.ADDPRODUTO = "adicione produtos!";
        this.SEMESTOQUE = "NÃO HÁ A QUANTIDADE EM ESTOQUE!";
        this.ERRO = "OCORREU UM ERRO!";
        this.ERROLOGIN = "erro ao salvar Login!";
        this.CADASTREPRO = "CADASTRE UM PROFISSIONAL!";
        this.AGENDADO = "agenda com sucesso!";
           this.RESET = "Reset concluido!";
           this.CAIXAFECHADO = "CAIXA FECHADO";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnOk = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblMens = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pbd/resource/animal.1.png"))); // NOI18N

        lblMens.setBackground(new java.awt.Color(255, 0, 0));
        lblMens.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        lblMens.setForeground(new java.awt.Color(51, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMens, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMens, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btnOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiaMensagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiaMensagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiaMensagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiaMensagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DiaMensagem dialog = new DiaMensagem(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblMens;
    // End of variables declaration//GEN-END:variables

    public void mostrarCamposInvalidos() {
        setLblMens(CAMPOS);
        setVisible(true);
    }
    public void mostrarReset() {
        setLblMens(RESET);
        setVisible(true);
    }

    public void mostrarErro() {
        setLblMens(ERRO);
        setVisible(true);
    }
    public void mostrarSemEstoque() {
        setLblMens(SEMESTOQUE);
        setVisible(true);
    }

    public void mostrarExclusaoNao() {
        setLblMens(EXCLUSAONAO);
        setVisible(true);
    }

    public void mostrarAddProduto() {
        setLblMens(ADDPRODUTO);
        setVisible(true);
    }

    public void mostrarErroLogin() {
        setLblMens(ERROLOGIN);
        setVisible(true);
    }

    public void mostrarAgendado() {
        setLblMens(AGENDADO);
        setVisible(true);
    }

    public void mostrarEdicao() {
        setLblMens(EDICAO);
        setVisible(true);
    }

    public void mostrarCadastrePRO() {
        setLblMens(CADASTREPRO);
        setVisible(true);
    }

    public void mostrarSenha() {
        setLblMens(SENHA);
        setVisible(true);
    }

    public void mostrarConfirmacao() {
        setLblMens(CADASTRO);
        setVisible(true);
    }

    public void mostrarExclusao() {
        setLblMens(EXCLUSAO);
        setVisible(true);
    }
    public void mostrarCaixa() {
        setLblMens(CAIXAFECHADO);
        setVisible(true);
    }

    /**
     * @return the btnOk
     */
    public javax.swing.JButton getBtnOk() {
        return btnOk;
    }

    /**
     * @return the lblMens
     */
    public javax.swing.JLabel getLblMens() {
        return lblMens;
    }

    public void setLblMens(String s) {
        lblMens.setText(s);
    }

    /**
     * @return the txtProduto
     */
}
