/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.pbd.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JInternalFrame;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Andre-Coude
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private CadastroAnimal cAnimal = new CadastroAnimal();
    private Clientes clientes = new Clientes();
    private Cadastros cadastros = new Cadastros();
    private CadastroCliente cCliente = new CadastroCliente();
    private CadastroFuncionario cFuncionario = new CadastroFuncionario();
    private CadastroFornecedor cFornecedor = new CadastroFornecedor();
    private CadastroProfissional cProfissioanl = new CadastroProfissional();
    private CadastroServico cServico = new CadastroServico();
    private Agenda agenda = new Agenda();
    private Vendas vendas = new Vendas();

    public TelaPrincipal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);

        ajustarInternalFrame(cAnimal);
        ajustarInternalFrame(clientes);
        ajustarInternalFrame(cadastros);
        ajustarInternalFrame(cCliente);
        ajustarInternalFrame(cFuncionario);
        ajustarInternalFrame(cFornecedor);
        ajustarInternalFrame(cProfissioanl);
        ajustarInternalFrame(agenda);
        ajustarInternalFrame(vendas);
        ajustarInternalFrame(cServico);
        
       
        setVisible(false);

        cadastros.getBtnProfissional().addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                getcProfissioanl().setVisible(rootPaneCheckingEnabled);
            }
        });
        cadastros.getBtnFornecedor().addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                getcFornecedor().setVisible(rootPaneCheckingEnabled);
            }
        });
        cadastros.getBtnAnimal1().addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                getcAnimal().setVisible(rootPaneCheckingEnabled);
            }
        });
        cadastros.getBtnCliente1().addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                getcCliente().setVisible(rootPaneCheckingEnabled);
            }
        });
        cadastros.getBtnFuncionario().addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                getcFuncionario().setVisible(rootPaneCheckingEnabled);
            }
        });
        cadastros.getVoltarMenu().addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                getPainelMenu().setVisible(true);
            }
        });
        clientes.getVoltarMenu().addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                getPainelMenu().setVisible(true);
            }
        });
        clientes.getVoltarMenu().addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                getPainelMenu().setVisible(true);
            }
        });
        agenda.getBtnSair().addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                getPainelMenu().setVisible(true);
            }
        });
         
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelMenu = new javax.swing.JPanel();
        btnClientes = new javax.swing.JButton();
        btnAgenda = new javax.swing.JButton();
        btnVendas = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnCadastros = new javax.swing.JButton();
        btnProdutos_serv = new javax.swing.JButton();
        btnFinanceiro = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnLogoff = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        paineArea = new javax.swing.JPanel();
        painelDesktop = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1024, 600));

        painelMenu.setBackground(new java.awt.Color(255, 255, 255));
        painelMenu.setPreferredSize(new java.awt.Dimension(1024, 600));
        painelMenu.setLayout(null);

        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pbd/resource/Layout App Clínica Botão 001.png"))); // NOI18N
        btnClientes.setBorder(null);
        btnClientes.setBorderPainted(false);
        btnClientes.setContentAreaFilled(false);
        btnClientes.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pbd/resource/Layout App Clínica Botão 001.1.png"))); // NOI18N
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        painelMenu.add(btnClientes);
        btnClientes.setBounds(20, 40, 280, 75);

        btnAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pbd/resource/Layout App Clínica Botão 002.png"))); // NOI18N
        btnAgenda.setBorder(null);
        btnAgenda.setBorderPainted(false);
        btnAgenda.setContentAreaFilled(false);
        btnAgenda.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pbd/resource/Layout App Clínica Botão 002.1.png"))); // NOI18N
        btnAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendaActionPerformed(evt);
            }
        });
        painelMenu.add(btnAgenda);
        btnAgenda.setBounds(20, 120, 280, 75);

        btnVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pbd/resource/Layout App Clínica Botão 003.png"))); // NOI18N
        btnVendas.setBorder(null);
        btnVendas.setBorderPainted(false);
        btnVendas.setContentAreaFilled(false);
        btnVendas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pbd/resource/Layout App Clínica Botão 003.1.png"))); // NOI18N
        btnVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendasActionPerformed(evt);
            }
        });
        painelMenu.add(btnVendas);
        btnVendas.setBounds(20, 200, 280, 75);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pbd/resource/Layout App Clínica Botão 004.png"))); // NOI18N
        jButton4.setToolTipText("");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pbd/resource/Layout App Clínica Botão 004.1.png"))); // NOI18N
        painelMenu.add(jButton4);
        jButton4.setBounds(20, 280, 280, 75);

        btnCadastros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pbd/resource/Layout App Clínica Botão 005.png"))); // NOI18N
        btnCadastros.setBorder(null);
        btnCadastros.setBorderPainted(false);
        btnCadastros.setContentAreaFilled(false);
        btnCadastros.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pbd/resource/Layout App Clínica Botão 005.1.png"))); // NOI18N
        btnCadastros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrosActionPerformed(evt);
            }
        });
        painelMenu.add(btnCadastros);
        btnCadastros.setBounds(20, 360, 280, 75);

        btnProdutos_serv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pbd/resource/Layout App Clínica Botão 006.png"))); // NOI18N
        btnProdutos_serv.setBorder(null);
        btnProdutos_serv.setBorderPainted(false);
        btnProdutos_serv.setContentAreaFilled(false);
        btnProdutos_serv.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pbd/resource/Layout App Clínica Botão 006.1.png"))); // NOI18N
        painelMenu.add(btnProdutos_serv);
        btnProdutos_serv.setBounds(20, 440, 280, 75);

        btnFinanceiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pbd/resource/Layout App Clínica Botão 007.png"))); // NOI18N
        btnFinanceiro.setBorder(null);
        btnFinanceiro.setBorderPainted(false);
        btnFinanceiro.setContentAreaFilled(false);
        btnFinanceiro.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pbd/resource/Layout App Clínica Botão 007.1.png"))); // NOI18N
        painelMenu.add(btnFinanceiro);
        btnFinanceiro.setBounds(20, 520, 280, 75);

        btnSair.setText("SAIR");
        btnSair.setAlignmentX(20.0F);
        btnSair.setAlignmentY(30.0F);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        painelMenu.add(btnSair);
        btnSair.setBounds(700, 560, 120, 23);

        btnLogoff.setText("LOGOFF");
        painelMenu.add(btnLogoff);
        btnLogoff.setBounds(863, 560, 110, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pbd/resource/fundoo1.png"))); // NOI18N
        jLabel1.setToolTipText("");
        painelMenu.add(jLabel1);
        jLabel1.setBounds(0, 0, 1400, 680);

        paineArea.setBackground(new java.awt.Color(255, 255, 255));
        paineArea.setPreferredSize(new java.awt.Dimension(1024, 600));
        paineArea.setLayout(null);

        javax.swing.GroupLayout painelDesktopLayout = new javax.swing.GroupLayout(painelDesktop);
        painelDesktop.setLayout(painelDesktopLayout);
        painelDesktopLayout.setHorizontalGroup(
            painelDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1410, Short.MAX_VALUE)
        );
        painelDesktopLayout.setVerticalGroup(
            painelDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );

        paineArea.add(painelDesktop);
        painelDesktop.setBounds(-10, 0, 1410, 680);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 1403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(paineArea, javax.swing.GroupLayout.DEFAULT_SIZE, 1392, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(paineArea, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        setBounds(0, 0, 1412, 691);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        // TODO add your handling code here:
        getPainelMenu().setVisible(false);
        getClientes().setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendasActionPerformed
        // TODO add your handling code here:
        getPainelMenu().setVisible(false);
        vendas.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnVendasActionPerformed

    private void btnCadastrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrosActionPerformed
        // TODO add your handling code here:
        getPainelMenu().setVisible(false);
        getCadastros().setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnCadastrosActionPerformed

    private void btnAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendaActionPerformed

        getPainelMenu().setVisible(false);
        getAgenda().setVisible(rootPaneCheckingEnabled);

        mudarVisaoData();
    }//GEN-LAST:event_btnAgendaActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        System.exit(WIDTH);
    }//GEN-LAST:event_btnSairActionPerformed

    public final void ajustarInternalFrame(JInternalFrame frame) {

        ((BasicInternalFrameUI) frame.getUI()).setNorthPane(null);
        frame.setBorder(null);
        painelDesktop.add(frame);
    }

    public void mudarVisaoData() {
        Date d = new Date(System.currentTimeMillis());
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");

        agenda.getLblDatal().setText(formato.format(d));
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgenda;
    private javax.swing.JButton btnCadastros;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnFinanceiro;
    private javax.swing.JButton btnLogoff;
    private javax.swing.JButton btnProdutos_serv;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnVendas;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel paineArea;
    private javax.swing.JDesktopPane painelDesktop;
    private javax.swing.JPanel painelMenu;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the cFuncionario
     */
    public CadastroFuncionario getcFuncionario() {
        return cFuncionario;
    }

    /**
     * @return the cAnimal
     */
    public CadastroAnimal getcAnimal() {
        return cAnimal;
    }

    /**
     * @return the clientes
     */
    public Clientes getClientes() {
        return clientes;
    }

    /**
     * @return the cadastros
     */
    public Cadastros getCadastros() {
        return cadastros;
    }

    /**
     * @return the cCliente
     */
    public CadastroCliente getcCliente() {
        return cCliente;
    }

    /**
     * @return the cFornecedor
     */
    public CadastroFornecedor getcFornecedor() {
        return cFornecedor;
    }

    /**
     * @return the cProfissioanl
     */
    public CadastroProfissional getcProfissioanl() {
        return cProfissioanl;
    }

    /**
     * @return the agenda
     */
    public Agenda getAgenda() {
        return agenda;
    }

    /**
     * @return the btnAgenda
     */
    public javax.swing.JButton getBtnAgenda() {
        return btnAgenda;
    }

    /**
     * @return the btnCadastros
     */
    public javax.swing.JButton getBtnCadastros() {
        return btnCadastros;
    }

    /**
     * @return the btnClientes
     */
    public javax.swing.JButton getBtnClientes() {
        return btnClientes;
    }

    /**
     * @return the btnFinanceiro
     */
    public javax.swing.JButton getBtnFinanceiro() {
        return btnFinanceiro;
    }

    /**
     * @return the btnProdutos_serv
     */
    public javax.swing.JButton getBtnProdutos_serv() {
        return btnProdutos_serv;
    }

    /**
     * @return the btnVendas
     */
    public javax.swing.JButton getBtnVendas() {
        return btnVendas;
    }

    /**
     * @return the painelMenu
     */
    public javax.swing.JPanel getPainelMenu() {
        return painelMenu;
    }

    /**
     * @return the btnLogoff
     */
    public javax.swing.JButton getBtnLogoff() {
        return btnLogoff;
    }

    /**
     * @return the btnSair
     */
    public javax.swing.JButton getBtnSair() {
        return btnSair;
    }

    /**
     * @return the cServico
     */
    public CadastroServico getcServico() {
        return cServico;
    }

}
